// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: protos/dynamodb.proto

package dynamodb_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DynamoDBService_StoreData_FullMethodName = "/dynamodb_service.DynamoDBService/StoreData"
)

// DynamoDBServiceClient is the client API for DynamoDBService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DynamoDBServiceClient interface {
	StoreData(ctx context.Context, in *StoreDataRequest, opts ...grpc.CallOption) (*StoreDataResponse, error)
}

type dynamoDBServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDynamoDBServiceClient(cc grpc.ClientConnInterface) DynamoDBServiceClient {
	return &dynamoDBServiceClient{cc}
}

func (c *dynamoDBServiceClient) StoreData(ctx context.Context, in *StoreDataRequest, opts ...grpc.CallOption) (*StoreDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreDataResponse)
	err := c.cc.Invoke(ctx, DynamoDBService_StoreData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DynamoDBServiceServer is the server API for DynamoDBService service.
// All implementations must embed UnimplementedDynamoDBServiceServer
// for forward compatibility.
type DynamoDBServiceServer interface {
	StoreData(context.Context, *StoreDataRequest) (*StoreDataResponse, error)
	mustEmbedUnimplementedDynamoDBServiceServer()
}

// UnimplementedDynamoDBServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDynamoDBServiceServer struct{}

func (UnimplementedDynamoDBServiceServer) StoreData(context.Context, *StoreDataRequest) (*StoreDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreData not implemented")
}
func (UnimplementedDynamoDBServiceServer) mustEmbedUnimplementedDynamoDBServiceServer() {}
func (UnimplementedDynamoDBServiceServer) testEmbeddedByValue()                         {}

// UnsafeDynamoDBServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DynamoDBServiceServer will
// result in compilation errors.
type UnsafeDynamoDBServiceServer interface {
	mustEmbedUnimplementedDynamoDBServiceServer()
}

func RegisterDynamoDBServiceServer(s grpc.ServiceRegistrar, srv DynamoDBServiceServer) {
	// If the following call pancis, it indicates UnimplementedDynamoDBServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DynamoDBService_ServiceDesc, srv)
}

func _DynamoDBService_StoreData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamoDBServiceServer).StoreData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DynamoDBService_StoreData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamoDBServiceServer).StoreData(ctx, req.(*StoreDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DynamoDBService_ServiceDesc is the grpc.ServiceDesc for DynamoDBService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DynamoDBService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dynamodb_service.DynamoDBService",
	HandlerType: (*DynamoDBServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StoreData",
			Handler:    _DynamoDBService_StoreData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/dynamodb.proto",
}
